import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'

import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang='en'>
                <body className={GeistSans.className}>
                    <ThemeProvider
                        attribute='class'
                        defaultTheme='system'
                        // defaultTheme='dark'
                        // defaultTheme='light'
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}
